---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-demo
# https://spacelift.io/blog/argocd
#
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

#sudo kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath={.data}
#echo bmdCR2ZQLWkwUVRTNFh0bQ== | base64 --decode
