apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mh-deployment
  labels:
    app: hello-mh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-mh
  template:
    metadata:
      labels:
        app: hello-mh
    spec:
      containers:
      - name: hello-mh
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-mh-service
spec:
  type: NodePort
  selector:
    app: hello-mh
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
